### ISSUE TITLE
Sync Error : NCC6348007

### ISSUE THREAD

**Issue by jhudsonWA** [WSDOT/HATS#140]
Action: LogMessage • Device Name: NCC6348007 • Device Model: iPad Air • Device System Version: 9.0.2 • Application Version: HATS-iOS 1.2 • Message: Sync Complete With Errors • Log:

 10-19-2015 07:49:17 AM:
Other Activity Record: Tree/Brush Control - Trimming Mechanical [10-06-2015 12:00 PM]  Could Not Be Saved To The Server. URL: http://hatsprod.wsdot.loc/Maintenance/Management/Activities/api/ios/AddOtherActivityRecord, Error Message: AddEditRecordDC -  usp_HATS_AddEvent:Success  usp_HATS_InsertDiscussion:Success  - AddEventRecord() System.Data.SqlClient.SqlException (0x80131904): A column insert or update conflicts with a rule imposed by a previous CREATE RULE statement. The statement was terminated. The conflict occurred in database 'CommitmentActivities', table 'dbo.Location', column 'Longitude'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at HATS.Classes.DataLayer.AddEditRecordDC.AddEventRecord(Nullable`1 userId)
ClientConnectionId:d400e4fd-8ab4-4fa6-a834-41beac8c443b.

10-19-2015 07:49:16 AM:
There Are No Feedback Attachments To Sync

10-19-2015 07:49:16 AM:
There Are No Activity Record Attachments To Sync

10-19-2015 07:49:16 AM:
There Are No Feedback Records To Sync

10-19-2015 07:49:16 AM:
There Are No Multiple Activity Pending Activity Records To Sync

10-19-2015 07:49:16 AM:
There Are No Other Pending Activity Records To Sync

10-19-2015 07:49:16 AM:
There Are No Feature Pending Activity Records To Sync

10-19-2015 07:49:16 AM:
There Are No Multiple Activity Records To Sync

10-19-2015 07:49:16 AM:
3 Other Activity Records To Sync

10-19-2015 07:49:16 AM:
There Are No Feature Activity Records To Sync

**Comment by jhudsonWA** [comment]
@joeschmit , This iPad is trying to submit a invalid Lat/Long. There is a database constant that makes sure that submitted Latitudes are between 0 and 90 and Longitudes are between -180 and 0.

I don't really have a good server side fix for this one, we will need to contact the user and fix the record.

**Comment by jhudsonWA** [comment]
I'll will add this check on records save in 1.3 so records don't get into this state.

**Comment by jhudsonWA** [comment]
@joeschmit Please also connect owners of SCC6433135, SCC6433014, ERC6349023. Theres users had the same error.

**Comment by joeschmit** [comment]
Done.
